/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MxAddSetSheet: typeof import('./src/components/MxAddSetSheet.vue')['default']
    MxButton: typeof import('./src/components/MxButton.vue')['default']
    MxExerciseCard: typeof import('./src/components/MxExerciseCard.vue')['default']
    MxGroupPanel: typeof import('./src/components/MxGroupPanel.vue')['default']
    MxHeader: typeof import('./src/components/MxHeader.vue')['default']
    MxHomePage: typeof import('./src/components/MxHomePage.vue')['default']
    MxListWorkoutDay: typeof import('./src/components/MxListWorkoutDay.vue')['default']
    MxTabBar: typeof import('./src/components/MxTabBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
