/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MxFooter: typeof import('./src/components/MxFooter.vue')['default']
    MxGroupPanel: typeof import('./src/components/MxGroupPanel.vue')['default']
    MxHeader: typeof import('./src/components/MxHeader.vue')['default']
    MxHomePage: typeof import('./src/components/MxHomePage.vue')['default']
    MxListWorkoutDay: typeof import('./src/components/MxListWorkoutDay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionBar: (typeof import('vant/es'))['ActionBar']
    VanActionBarButton: (typeof import('vant/es'))['ActionBarButton']
    VanActionBarIcon: (typeof import('vant/es'))['ActionBarIcon']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCard: (typeof import('vant/es'))['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: (typeof import('vant/es'))['CellGroup']
    VanCheckbox: (typeof import('vant/es'))['Checkbox']
    VanCheckboxGroup: (typeof import('vant/es'))['CheckboxGroup']
    VanCol: (typeof import('vant/es'))['Col']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: (typeof import('vant/es'))['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRow: (typeof import('vant/es'))['Row']
    VanSubmitBar: (typeof import('vant/es'))['SubmitBar']
    VanSwipe: (typeof import('vant/es'))['Swipe']
    VanSwipeItem: (typeof import('vant/es'))['SwipeItem']
    VanTag: (typeof import('vant/es'))['Tag']
  }
}
